export interface Niche {
  name: string;
  focusAreas: string[];
}

export const FIXED_NICHES: Niche[] = [
  {
    name: "Content Marketing",
    focusAreas: [
      "Blog Writing & Publishing",
      "Educational Content Creation",
      "Long-form Authority Content",
      "Content Distribution & Syndication",
      "Guest Posting & Collaborative Content",
      "Content Strategy & Planning",
      "Content Calendar & Workflow Systems",
      "Niche Positioning & Audience Definition",
      "Competitor Content Analysis",
      "Storytelling & Narrative Writing",
      "Personal Branding Through Content",
      "Thought Leadership Content",
      "Brand Voice & Tone Development",
      "Content Repurposing & Reformatting",
      "Content Optimization & Refreshing",
      "Content Performance & Analytics",
      "SEO-Driven Content Writing",
      "Content-Led Lead Generation",
      "Building an Audience with Content",
      "Newsletter & Email Content",
      "Paid Content & Productized Writing",
    ],
  },
  {
    name: "SEO",
    focusAreas: [
      "Keyword Research",
      "Search Intent Optimization",
      "Competitor SEO Analysis",
      "Topical Authority & Clustering",
      "SEO Strategy & Roadmapping",
      "On-Page SEO",
      "Content Optimization & Refreshing",
      "Title Tags, Meta & Click Optimization",
      "Internal Linking Strategy",
      "Programmatic SEO",
      "Technical SEO Fundamentals",
      "Site Speed & Core Web Vitals",
      "Crawlability & Indexation",
      "Schema Markup & Structured Data",
      "Mobile SEO",
      "Link Building Strategies",
      "Digital PR & Brand Mentions",
      "Local SEO & Citations",
      "E-E-A-T & Authority Building",
      "SEO Analytics & Reporting",
      "Rank Tracking & Performance",
      "Algorithm Updates & Adaptation",
    ],
  },
  {
    name: "X / Twitter Growth",
    focusAreas: [
      "Tweet Writing (Hooks & Formats)",
      "Thread Creation & Structure",
      "Content Systems & Consistency",
      "Content Batching & Scheduling",
      "Writing for Engagement vs. Reach",
      "Audience Building Strategy",
      "Profile Optimization & Positioning",
      "Follower Growth Tactics",
      "Niche Domination on X",
      "Cross-Platform Audience Funneling",
      "Engagement & Virality Tactics",
      "Reply & Comment Strategy",
      "Leveraging Trends & Moments",
      "Collaboration & Shoutout Strategy",
      "Community Building on X",
      "Personal Brand Positioning",
      "Niche Authority Building",
      "Storytelling for Personal Brand",
      "Reputation & Trust on X",
      "Monetization via X/Twitter",
      "Selling Through X Content",
      "Newsletter & Lead Gen from X",
      "Sponsorships & Brand Deals on X",
    ],
  },
  {
    name: "Reddit Marketing",
    focusAreas: [
      "Finding Target Subreddits",
      "Karma Building & Account Warmup",
      "Community Rules & Culture Reading",
      "Account Credibility & Trust Building",
      "Post Writing (Non-spam, Native Style)",
      "Viral Post Frameworks",
      "Title Writing for Reddit",
      "Image & Link Post Strategy",
      "AMA Strategy & Execution",
      "Comment Marketing Strategy",
      "Promotion Without Getting Banned",
      "Native Advertising on Reddit",
      "Subtle Brand Mentions & Soft Sells",
      "Competitor & Audience Research",
      "Trend Spotting via Reddit",
      "Pain Point Mining from Communities",
      "Product Validation via Reddit",
      "Driving Traffic from Reddit",
      "Building a Funnel from Reddit",
      "Reddit Ads Strategy",
      "Long-term Reddit Brand Presence",
    ],
  },
  {
    name: "Email Marketing",
    focusAreas: [
      "List Building & Lead Capture",
      "Opt-in Page & Form Optimization",
      "Lead Magnet Strategy for Email",
      "List Segmentation from Day One",
      "Newsletter Writing",
      "Sales Email Copywriting",
      "Subject Lines & Open Rate Optimization",
      "Email Personalization & Dynamic Content",
      "Storytelling in Emails",
      "Welcome Sequence Strategy",
      "Nurture Sequence Design",
      "Abandoned Cart & Behavioral Emails",
      "Post-Purchase & Onboarding Sequences",
      "Automated Email Funnels",
      "Retention & Re-engagement Emails",
      "Win-Back Campaign Strategy",
      "Subscriber Loyalty & Community",
      "Reducing Unsubscribes & Churn",
      "Deliverability & Inbox Placement",
      "Email Analytics & Performance Tracking",
      "A/B Testing Email Campaigns",
      "Email Compliance & Best Practices",
    ],
  },
  {
    name: "Lead Generation",
    focusAreas: [
      "Traffic & Lead Sources",
      "Organic Lead Generation",
      "Paid Lead Generation",
      "Cold Outreach & Prospecting",
      "Social Selling",
      "Landing Pages",
      "Lead Magnets",
      "Form & CTA Optimization",
      "Conversion Copywriting",
      "Offer Creation & Positioning",
      "Funnel Design",
      "CRO (Conversion Rate Optimization)",
      "Upsells, Downsells & Funnel Sequencing",
      "A/B Testing & Optimization",
      "Lead Nurturing & Email Sequences",
      "Lead Scoring & Qualification",
      "Segmentation & Personalization",
      "Social Proof & Case Studies",
      "Trust Signals & Objection Handling",
      "Buyer Psychology & Persuasion",
    ],
  },
  {
    name: "Sales / Outreach",
    focusAreas: [
      "Cold Email Outreach",
      "LinkedIn Outreach Strategy",
      "Cold Calling Scripts & Tactics",
      "Multi-channel Outreach Sequences",
      "Personalization at Scale",
      "Sales Messaging & Scripts",
      "Offer Positioning",
      "Value Proposition Writing",
      "Pain-Focused Messaging",
      "Follow-Up Sequences",
      "Breakup Email Strategy",
      "CRM & Pipeline Management",
      "Timing & Cadence Optimization",
      "Objection Handling",
      "Closing & Conversion Tactics",
      "Negotiation Tactics",
      "Proposal & Pricing Strategy",
      "Social Proof in Sales",
      "Relationship-Based Selling",
      "Referral & Warm Intro Strategy",
      "Building Long-term Client Relationships",
    ],
  },
];
