import type { Metadata } from "next";
import "./globals.css";
import { geist, ibmPlexSerif, kumbhSans } from "./fonts";
import { Providers } from "@/components/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${ibmPlexSerif.variable} ${kumbhSans.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
