import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms and Conditions | HackrPost",
  description: "Terms and Conditions for HackrPost.",
};

const sections = [
  {
    title: "Eligibility",
    paragraphs: [
      "You must be at least 13 years of age to use HackrPost. By using the Service, you represent that you meet this requirement and that all information you provide is accurate and complete.",
    ],
  },
  {
    title: "Accounts",
    paragraphs: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate these Terms.",
    ],
  },
  {
    title: "Use of the Service",
    paragraphs: [
      "HackrPost provides a platform to generate and automatically publish posts to your X (Twitter) account. You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:",
    ],
    items: [
      "Use the Service to post content that is illegal, harmful, defamatory, abusive, or harassing",
      "Violate X's Terms of Service or Community Guidelines",
      "Use the Service to send spam or unsolicited communications",
      "Attempt to reverse engineer, hack, or disrupt the Service",
      "Use the Service to infringe on the intellectual property rights of others",
      "Resell or sublicense access to the Service without our written consent",
    ],
  },
  {
    title: "Content",
    paragraphs: [
      "You retain ownership of any content published to your X account through HackrPost. By using the Service, you grant us a limited license to generate, store, and publish content on your behalf as instructed by your settings and preferences.",
      "You are solely responsible for reviewing and approving the content published through your account. We are not liable for any content generated by the Service that you choose to publish.",
    ],
  },
  {
    title: "X (Twitter) Integration",
    paragraphs: [
      "HackrPost connects to your X account via OAuth. By connecting your account, you authorize us to post on your behalf according to your configured schedule and preferences. You may revoke this access at any time through your X account settings. We are not affiliated with or endorsed by X Corp.",
    ],
  },
  {
    title: "Subscriptions and Payments",
    paragraphs: [
      "Access to certain features of HackrPost requires a paid subscription. By subscribing, you agree to pay the applicable fees as displayed at the time of purchase. All payments are processed securely through our third-party payment provider.",
    ],
    items: [
      "Subscriptions automatically renew at the end of each billing period unless cancelled",
      "You may cancel your subscription at any time from your account settings",
      "Cancellations take effect at the end of the current billing period; no partial refunds are issued",
      "We reserve the right to change pricing with reasonable advance notice",
    ],
  },
  {
    title: "Refund Policy",
    paragraphs: [
      "We offer refunds within 7 days of your initial purchase if you are not satisfied with the Service. After this period, all sales are final. To request a refund, contact us at the email address below.",
    ],
  },
  {
    title: "Intellectual Property",
    paragraphs: [
      "All content, design, code, and materials comprising the HackrPost platform - excluding content generated for and published to your X account - are the intellectual property of HackrPost and are protected by applicable copyright and trademark laws. You may not copy, reproduce, or distribute any part of the platform without our written permission.",
    ],
  },
  {
    title: "Disclaimer of Warranties",
    paragraphs: [
      "The Service is provided \"as is\" and \"as available\" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components. We do not guarantee any specific results from use of the Service, including growth of your X account.",
    ],
  },
  {
    title: "Limitation of Liability",
    paragraphs: [
      "To the fullest extent permitted by law, HackrPost shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss of data, loss of revenue, or damage to reputation. Our total liability to you shall not exceed the amount you paid us in the 3 months preceding the claim.",
    ],
  },
  {
    title: "Indemnification",
    paragraphs: [
      "You agree to indemnify and hold harmless HackrPost and its team members from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.",
    ],
  },
  {
    title: "Termination",
    paragraphs: [
      "We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for conduct that we determine violates these Terms or is otherwise harmful to other users, us, or third parties. Upon termination, your right to use the Service ceases immediately.",
    ],
  },
  {
    title: "Changes to These Terms",
    paragraphs: [
      "We may update these Terms from time to time. We will notify you of material changes by email and update the date at the top of this page. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.",
    ],
  },
  {
    title: "Governing Law",
    paragraphs: [
      "These Terms are governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be resolved through good-faith negotiation, or if necessary, through binding arbitration or the courts of competent jurisdiction.",
    ],
  },
] as const;

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms and Conditions"
      title="Clear rules for using HackrPost."
      lastUpdated="April 14, 2026"
      intro={[
        "Please read these Terms and Conditions carefully before using HackrPost (\"the Service\"), operated by HackrPost (\"we\", \"us\", or \"our\").",
        "By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, please do not use the Service.",
      ]}
      sections={[...sections]}
    />
  );
}
